language: php

sudo: false

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - nginx

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0
  - 7.1
  - nightly

env:
  - WP_VERSION=nightly
  - WP_VERSION=latest
  - WP_VERSION=4.7.2

matrix:
  fast_finish: true

before_install:
  - export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
  - export PATH="$TRAVIS_BUILD_DIR/bin:$PATH"
  - export TNW_TPL_DIR="$TRAVIS_BUILD_DIR/tpl"
  - composer install -n --prefer-dist --no-suggest

install:
  - tnw-install-nginx
  - tnw-install-wordpress
  - tnw-prepare-codeception
  - tnw-install-wpcs

script:
  ### Assert that WordPress is served at `http://wp.dev:8080`
  # Echo the WordPress Homepage source code
  - curl -vsf 'http://wp.dev:8080' &> /dev/stdout

  # Show the wp-config.php source code
  - cat /tmp/wordpress/wp-config.php

  # There should be nothing in the Nginx error log
  - cat /tmp/error.log

  # Display the WordPress version.
  - wp core version --path=/tmp/wordpress

  # Show a list of installed coding standards
  - phpcs -i
